### PR TITLE
Guestacc

### PR DESCRIPTION
**Pull request by erkkki**

### CODE REVIEW

**Review by stuudmuffin — DISMISSED** [review]
After merging the new auth code, I updated the beta-auth branch from the master so it would match. 

I'm unsure if anything in this pull request is new or different from the master. git handles file changes from different branches into master fairly well. So merges from one branch to another, unless specifically testing a variation of code, is not really needed.

**Comment by erkkki** [comment]
ah.. merge conflict is because altlogin.php is now old login.php, I think.

**Comment by zackman0010** [comment]
Can you confirm that your changes to the code still work with the base changed?

**Comment by erkkki** [comment]
Done.

**Comment by erkkki** [comment]
I mean altlogin is working.. Can't test auth login and user level things there. But no more conflicts.

**Comment by zackman0010** [comment]
@stuudmuffin Want to go ahead and merge this?

**Comment by zackman0010** [comment]
Changing it back to beta-auth and merging it. I'm gonna test and make sure it all works in production before I merge back into master.

**Pull request merged**
